project:
  type: website
  output-dir: docs

website:
  title: "A Quarto Website"
  navbar:
    left:
        - Index.qmd
        - about.qmd
        - References.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
