---
title: "topic modelling"
author: "Kelly-Robyn Singh, Natalie Alexander, Thabo Dube"
date: "2023-10-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load libraries
library(tidyverse)
library(tidytext)
library(topicmodels)

load("sona.RData")

```

```{r}

# removing custom stop words that frequently appear 
custom_stopwords <- c("with", "regards", "to", "and", "other", "custom", "stopwords", "you", "want", "south", "africa", "madame","speaker")

# removed stop words 
# Define your replace_reg and unnest_reg
replace_reg <- "(http.*?(\\s|.$))|(www.*?(\\s|.$))|&amp;|&lt;|&gt;"
rnum <- "\\d+"
unnest_reg <- "[^\\w_#@']"


# tidy dataset, removed numbers
tidy_sona<- sona %>%
  mutate(speech= str_trim(speech, side= "left")) %>%
  mutate(speech = str_replace_all(speech, replace_reg, "")) %>%
  mutate(speech=str_replace_all( speech, "[[:punct:]]", ""))%>%
  mutate(speech = str_replace_all(speech , rnum , ""))  %>%
  mutate(filename = sub("\\.txt$", "", filename))

# clean and bigrams 
  bigram_sona <- tidy_sona %>%
    unnest_tokens(bigram, speech, token ="ngrams", n=2, to_lower = TRUE) %>%
    separate(bigram, c("word1", "word2"), sep = " ")%>%
    filter(!word1 %in% stop_words$word & !word2 %in% stop_words$word) %>%
  filter(!(word1 %in% custom_stopwords | word2 %in% custom_stopwords)) %>%
  unite(bigram, word1, word2, sep = " ")
```

```{r}
# LDA 

# tdf
  speech_tdf <- bigram_sona %>%
    group_by(filename, bigram) %>%
    count() %>%
    ungroup()
  
  dtm_speech <- speech_tdf %>%
    cast_dtm(filename, bigram, n)
  
speech_lda <- LDA(dtm_speech, k=8, method = "Gibbs", control = list(seed=123))
  
library(tm)
  
# Extract top words
top_words <- get_terms(speech_lda, 6)  # Change 10 to the number of top words you want

# View the top words for each topic
top_words
as_tibble(top_words)
  
```
```{r}

# convert to tidy 
speech_lda <- tidy(speech_lda, matrix = "gamma")

# convert to tibble 
tidy_sona <- as_tibble(tidy_sona)

# join the LDA topics and the sona data 
speech_g <- speech_lda %>%
  left_join(tidy_sona, by = c("document" = "filename")) %>%
  spread(key = topic, value = gamma, sep = "_")
  
# group by filename/document 
speech_g %>%
  group_by(document) %>%
  summarise(ntopic1= sum(topic_1 > 0.5 ))

# group by topics 
top_term<- speech_lda %>%
  group_by(topic) %>%
  top_n(10, gamma) %>%
  ungroup(topic, -gamma)

# plot the topic and respective filenames its associated with 
top_term %>% 
  mutate(document = reorder(document, gamma)) %>%
  ggplot(aes(document,gamma, fill = factor(topic))) +
  geom_col(show.legend = F) +
  facet_wrap(~topic, scales = "free") +
  coord_flip()
```


