---
title: "References"
---

-   Arndt, C., Davies, R., Gabriel, S., Harris, L., Makrelov, K., Modise, B., Robinson, S., Simbanegavi, W., Van Seventer, D., & Anderson, L. (2020). Impact of Covid-19 on the South African economy. Southern Africa-Towards Inclusive Economic Development Working Paper, 111.

-   Bhardwaj A, Narayan Y, Vanraj P, Dutta M (2015) Sentiment analysis for indian stock market prediction using sensex and nifty. In: Procedia computer science, vol 70, pp 85--91

-   Biraj Dahal, Kumar, S. and Li, Z. (2019). Topic modeling and sentiment analysis of global climate change tweets. Social Network Analysis and Mining, \[online\] 9(1). doi:https://doi.org/10.1007/s13278-019-0568-8.

-   Blei, D.M., Ng, A.Y. and Jordan, M.I., 2003. Latent dirichlet allocation. *Journal of machine Learning research*, *3*(Jan), pp.993-1022.

-   Blei, D.M. and Lafferty, J. (2006). Dynamic Topic Models. \[online\] ResearchGate. Available at: https://www.researchgate.net/publication/221345245_Dynamic_Topic_Models \[Accessed 21 Oct. 2023\].

-   Guo, L., Vargo, C.J., Pan, Z., Ding, W. and Ishwar, P. (2016). Big Social Data Analytics in Journalism and Mass Communication. Journalism & Mass Communication Quarterly, 93(2), pp.332--359. doi:https://doi.org/10.1177/1077699016639231.

-    Hong, L. and Davison, B.D., 2010, July. Empirical study of topic modeling in twitter. In Proceedings of the first workshop on social media analytics (pp. 80-88).

-   Obeng-Odoom, F. (2020). The African Continental Free Trade Area. American Journal of Economics and Sociology, 79(1), 167-197.

-   Rao T, Srivastava S (2012) Analyzing stock market movements using Twitter sentiment analysis. In: ASONAM\'12 Proceedings of the 2012 international conference on advances in social networks analysis and mining (ASONAM 2012), pp 119--123

-   Singla Z, Randhawa S, Jain S (2017) Statistical and sentiment analysis of consumer product reviews. In: 8th International conference on computing, communication and networking technologies (ICCCNT), pp 1--6

-   Tang, J., Zhang, M. and Mei, Q., 2013, August. One theme in all views: modeling consensus topics in multiple contexts. In Proceedings of the 19th ACM SIGKDD international conference on Knowledge discovery and data mining (pp. 5-13).

-   Xie, R., Kai, S., Dickson K.W. Chiu and Wang, Y. (2021). Exploring Public Response to COVID-19 on Weibo with LDA Topic Modeling and Sentiment Analysis. Data and Information Management, \[online\] 5(1), pp.86--99. doi:https://doi.org/10.2478/dim-2020-0023.
